### ISSUE TITLE
build.xml:36 refers to ./classes/ which is missing

### ISSUE THREAD

**Issue by mmokrejs** [imilne/tablet#6] opened 2019-03-25 09:45 UTC
Hi,
  how can I build tablet from sources?

```
$ ant 
!!! ERROR: Package jython was not found!
!!! ERROR: Package jython was not found!
Buildfile: /scratch/var/tmp/portage/sci-biology/tablet-9999/work/tablet-9999/build.xml

init:

compile:

BUILD FAILED
/scratch/var/tmp/portage/sci-biology/tablet-9999/work/tablet-9999/build.xml:36: destination directory "/scratch/var/tmp/portage/sci-biology/tablet-9999/work/tablet-9999/classes" does not exist or is not a directory

Total time: 0 seconds
$
```

**Comment by imilne** [comment] 2019-03-25 09:48
Just make a 'classes' folder manually. We'll update the script at some point - it's just a legacy error from when it used to be SVN before GitHub.

**Comment by mmokrejs** [comment] 2019-03-25 09:53
Hi Ian, thank you, I see now the *.class files filled in there but what else?

Aha, `ant jar` seems to give me a jar file. Is there a documentation how to build it?

Probably `./lib/picard-1.113.txt` could be dropped as you switched from `picard` to `htsjdk`.

**Comment by imilne** [comment] 2019-03-25 09:57
Sorry, no docs yet (and good point). You're pretty much there though:

ant jar (to build)
java -jar lib/tablet.jar (to run)

We've not had much time of late to work on Tablet, so picard/htsjdk stuff may well be out of date, but the versions in the repo will be what's needed for building it for now.

**Comment by mmokrejs** [comment] 2019-03-25 10:11
OK, I got the thing installed but two more nit picks.

The version number displayed is `xx.xx.xx.xx`, I see it in `build.xml` but is maybe defined also elsewhere.

Second, which `java` version is required to run it? I have 1.8.`0_202`.
```
java.lang.UnsupportedClassVersionError: tablet/gui/Tablet : Unsupported major.minor version 52.00 52.052at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)r.java:142)2)      at java.net.URLClassLoader.access$100(URLClassLoader.java:64)2)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354):64)2)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348):64)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425):347)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)ava:308)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
```

**Comment by imilne** [comment] 2019-03-25 10:13
Development versions will always show the x's -  that's because it was designed to be distributed with Install4j (which bundles in the final version number). It also stops it logging and checking for updates against our servers which only the 'public' releases do.

Java 1.8 should be fine. It may work ok with JRE11, but as I say, we've not been active on it for a bit and 1.8 is what was used for what's currently committed.

**Comment by mmokrejs** [comment] 2019-03-25 10:39
Also released source tarballs (https://github.com/cropgeeks/tablet/archive/1.17.08.17.tar.gz) lack `lib/htsjdk-2.0.11.jar` file, which is otherwise present in git source repo tree and in released binary tarballs. Ah, yeah, there was no release since the fix in https://github.com/cropgeeks/tablet/commit/326733ac9e5529a9bc22e6bc3ce256188e5c00c8 .

**Closed as completed** 2019-05-28 08:59 UTC
